### ISSUE TITLE
paygw_mollie\privacy\provider::get_contexts_for_userid fails

### ISSUE THREAD

**Issue by analystcmyk** [sebsoftnl/moodle-paygw_mollie#1]
Exception occurred while processing privacy data
 
Exception occurred while calling paygw_mollie\privacy\provider::get_contexts_for_userid.
This means that plugin paygw_mollie did not complete the processing of data. The following exception information may be passed on to the plugin developer:
Return value of paygw_mollie\privacy\provider::get_contexts_for_userid() must be an instance of core_privacy\local\request\contextlist, none returned

 
#0 /var/www/moodle.site/lib/moodlelib.php(7997): paygw_mollie\privacy\provider::get_contexts_for_userid()
#1 /var/www/moodle.site/privacy/classes/manager.php(578): component_class_callback()
#2 /var/www/moodle.site/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#3 /var/www/moodle.site/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback()
#4 /var/www/moodle.site/admin/tool/dataprivacy/classes/task/process_data_request_task.php(94): core_privacy\manager->get_contexts_for_userid()
#5 /var/www/moodle.site/lib/cronlib.php(341): tool_dataprivacy\task\process_data_request_task->execute()
#6 /var/www/moodle.site/lib/cronlib.php(198): cron_run_inner_adhoc_task()
#7 /var/www/moodle.site/lib/cronlib.php(76): cron_run_adhoc_tasks()
#8 /var/www/moodle.site/admin/cli/cron.php(178): cron_run()
#9 {main}

**Comment by ewallah** [comment]
The function get_contexts_for_userid is not returning anything, 1 extra line fixes the problem:
```
        $contextlist = new contextlist();
        $contextlist->add_system_context();
        +return $contextlist;

```

**Comment by rogiervandongen** [comment]
@ewallah @analystcmyk Thanks for participating in the plugin and providing the issue.
It should be fixed according to commit https://github.com/sebsoftnl/moodle-paygw_mollie/commit/766e62fa2f884fd7c89d302b2b4096277cb1b259

Cheers :)
